import json
import logging
import re
from datetime import UTC, datetime
from decimal import Decimal

from pydantic import ValidationError
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.config import Settings, get_settings
from app.models import AIRecommendation, CostOpportunity, Item, Supplier
from app.schemas.api import PaginatedResponse, PaginationParams
from app.schemas.recommendations import (
    GeneratedRecommendation,
    RecommendationContext,
    RecommendationResponse,
)
from app.services.llm import LLMProviderError, OpenAIResponsesClient, RecommendationLLM

logger = logging.getLogger(__name__)
PROMPT_VERSION = "phase1-v1"
NUMBER_PATTERN = re.compile(r"(?<![A-Za-z])[-+]?\d[\d,]*(?:\.\d+)?")

SYSTEM_PROMPT = """You are a procurement analytics advisor.

You receive verified analytical results generated by a deterministic procurement analytics engine.

Do not invent facts. Do not invent suppliers. Do not invent prices. Do not invent savings. Do not
alter numerical values supplied in the context. Do not introduce any numerical value that is absent
from the context. Your job is to explain the verified findings and recommend reasonable procurement
actions. Estimated savings are opportunities, not guaranteed savings. Do not recommend eliminating
suppliers solely because they are expensive. Consider price, quality, delivery and contract
performance. Do not claim external benchmarks, competitors, market prices, or contract terms unless
they are supplied. If the context is insufficient, say so explicitly.

For PRICE_OPTIMIZATION consider negotiation, benchmark review, competitive bidding, or alternative
supplier evaluation. For CONTRACT_LEAKAGE consider compliance review, contract expansion, or policy
review. For SUPPLIER_CONSOLIDATION recommend evaluating volume consolidation or strategic
negotiation, never automatic elimination. For SUPPLIER_PERFORMANCE consider performance review,
corrective action, renegotiation, or alternative supplier evaluation.
"""


class NumericalPreservationError(ValueError):
    pass


class RecommendationService:
    def __init__(self, session: Session, settings: Settings | None = None):
        self.session = session
        self.settings = settings or get_settings()

    def _context(self, opportunity_id: int) -> RecommendationContext | None:
        row = self.session.execute(
            select(
                CostOpportunity.opportunity_id,
                CostOpportunity.opportunity_type,
                Item.item_name,
                Supplier.supplier_name,
                CostOpportunity.actual_price,
                CostOpportunity.benchmark_price,
                CostOpportunity.price_variance_percent,
                CostOpportunity.quantity,
                CostOpportunity.estimated_savings,
                CostOpportunity.review_spend,
                CostOpportunity.confidence_score,
                CostOpportunity.supporting_metrics,
            )
            .join(Item, CostOpportunity.item_id == Item.item_id)
            .outerjoin(Supplier, CostOpportunity.supplier_id == Supplier.supplier_id)
            .where(CostOpportunity.opportunity_id == opportunity_id)
        ).one_or_none()
        if row is None:
            return None
        metrics = row.supporting_metrics or {}

        def metric(name: str) -> Decimal | None:
            value = metrics.get(name)
            return Decimal(str(value)) if value is not None else None

        return RecommendationContext(
            opportunity_id=int(row.opportunity_id),
            opportunity_type=row.opportunity_type,
            item=row.item_name,
            supplier=row.supplier_name,
            actual_price=Decimal(row.actual_price) if row.actual_price is not None else None,
            benchmark_price=(
                Decimal(row.benchmark_price) if row.benchmark_price is not None else None
            ),
            price_variance_percent=(
                Decimal(row.price_variance_percent)
                if row.price_variance_percent is not None
                else None
            ),
            quantity=Decimal(row.quantity) if row.quantity is not None else None,
            estimated_savings=Decimal(row.estimated_savings),
            review_spend=Decimal(row.review_spend),
            confidence_score=Decimal(row.confidence_score),
            supplier_score=metric("supplier_score"),
            quality_rejection_rate=metric("supplier_rejection_rate")
            or metric("quality_rejection_rate"),
            late_delivery_rate=metric("supplier_late_delivery_rate")
            or metric("late_delivery_rate"),
            contract_compliance_rate=metric("supplier_contract_compliance_rate")
            or metric("contract_compliance_rate"),
            supporting_metrics=metrics,
        )

    @staticmethod
    def _numbers(value: object) -> set[Decimal]:
        found: set[Decimal] = set()
        if isinstance(value, dict):
            for nested in value.values():
                found.update(RecommendationService._numbers(nested))
        elif isinstance(value, list):
            for nested in value:
                found.update(RecommendationService._numbers(nested))
        elif isinstance(value, (int, float, Decimal)) and not isinstance(value, bool):
            found.add(Decimal(str(value)))
        elif isinstance(value, str):
            for match in NUMBER_PATTERN.findall(value):
                found.add(Decimal(match.replace(",", "")))
        return found

    @classmethod
    def validate_numerical_preservation(
        cls, result: GeneratedRecommendation, context: RecommendationContext
    ) -> None:
        if result.estimated_impact != context.expected_impact:
            raise NumericalPreservationError(
                "estimated_impact differs from the deterministic context"
            )
        allowed = cls._numbers(context.model_dump(mode="json"))
        output_text = " ".join(
            filter(
                None,
                [
                    result.title,
                    result.summary,
                    result.reasoning,
                    result.recommended_action,
                    result.risks,
                    *result.next_steps,
                ],
            )
        )
        invented = cls._numbers(output_text) - allowed
        if invented:
            raise NumericalPreservationError(
                "recommendation text introduced numerical values not present in context"
            )

    @staticmethod
    def _fallback(context: RecommendationContext, reason: str) -> GeneratedRecommendation:
        actions = {
            "PRICE_OPTIMIZATION": (
                "Review the verified item benchmark and evaluate price negotiation, competitive "
                "bidding, or qualified alternatives without assuming guaranteed savings."
            ),
            "CONTRACT_LEAKAGE": (
                "Review the off-contract purchases, applicable agreements, and procurement policy "
                "before deciding whether contract coverage should be expanded."
            ),
            "SUPPLIER_CONSOLIDATION": (
                "Evaluate volume-based negotiation and supplier consolidation scenarios while "
                "preserving resilience, quality, and delivery requirements."
            ),
            "SUPPLIER_PERFORMANCE": (
                "Conduct a supplier performance review and consider corrective action, "
                "renegotiation, or qualified alternatives based on verified evidence."
            ),
        }
        impact_label = (
            "potential savings" if context.estimated_savings > 0 else "spend requiring review"
        )
        return GeneratedRecommendation(
            title=f"Procurement review for {context.item}",
            summary=(
                f"The deterministic engine identified a {context.opportunity_type} finding for "
                f"{context.item}. The estimated impact is {context.expected_impact} as "
                f"{impact_label}; it is not guaranteed savings."
            ),
            reasoning=(
                "This recommendation uses only stored benchmark, spend, supplier-performance, and "
                f"confidence facts. Automated narrative fallback was used because {reason}."
            ),
            recommended_action=actions[context.opportunity_type],
            estimated_impact=context.expected_impact,
            risks=(
                "Validate commercial feasibility, service continuity, quality, delivery, and "
                "contract requirements before action."
            ),
            next_steps=[
                "Confirm the underlying purchase-order scope with procurement owners.",
                "Document the commercial decision and track realized impact separately.",
            ],
        )

    def generate(
        self,
        opportunity_id: int,
        *,
        client: RecommendationLLM | None = None,
        force: bool = False,
    ) -> AIRecommendation | None:
        context = self._context(opportunity_id)
        if context is None:
            return None

        key = self.settings.openai_api_key
        if client is None and key is not None and key.get_secret_value():
            client = OpenAIResponsesClient(
                api_key=key.get_secret_value(),
                model=self.settings.openai_model,
                timeout_seconds=self.settings.openai_timeout_seconds,
            )

        generated: GeneratedRecommendation | None = None
        model_name = client.model_name if client else "deterministic-fallback"
        fallback_reason = "no server-side API key was configured"
        if client is not None:
            fallback_reason = "the language-model response was unavailable or invalid"
            context_json = json.dumps(context.model_dump(mode="json"), indent=2)
            schema = GeneratedRecommendation.model_json_schema()
            for attempt in range(2):
                try:
                    raw = client.generate(
                        system_prompt=SYSTEM_PROMPT,
                        context_json=context_json,
                        schema=schema,
                    )
                    candidate = GeneratedRecommendation.model_validate(raw)
                    self.validate_numerical_preservation(candidate, context)
                    generated = candidate
                    break
                except (
                    LLMProviderError,
                    NumericalPreservationError,
                    ValidationError,
                    TypeError,
                    ValueError,
                ) as exc:
                    logger.warning(
                        "Recommendation generation attempt %s failed for opportunity %s: %s",
                        attempt + 1,
                        opportunity_id,
                        type(exc).__name__,
                    )
        if generated is None:
            generated = self._fallback(context, fallback_reason)
            model_name = "deterministic-fallback"

        existing = self.session.scalar(
            select(AIRecommendation).where(
                AIRecommendation.opportunity_id == opportunity_id,
                AIRecommendation.model_name == model_name,
                AIRecommendation.prompt_version == PROMPT_VERSION,
            )
        )
        if existing is not None and not force:
            return existing
        values = {
            "title": generated.title,
            "summary": generated.summary,
            "reasoning": generated.reasoning,
            "recommended_action": generated.recommended_action,
            "estimated_impact": generated.estimated_impact,
            "risks": generated.risks,
            "next_steps": generated.next_steps,
            "context_snapshot": context.model_dump(mode="json"),
            "created_at": datetime.now(UTC),
        }
        if existing is None:
            existing = AIRecommendation(
                opportunity_id=opportunity_id,
                model_name=model_name,
                prompt_version=PROMPT_VERSION,
                **values,
            )
            self.session.add(existing)
        else:
            for field, value in values.items():
                setattr(existing, field, value)
        self.session.flush()
        return existing

    @staticmethod
    def _response(row) -> RecommendationResponse:
        return RecommendationResponse(
            recommendation_id=int(row.recommendation_id),
            opportunity_id=int(row.opportunity_id),
            opportunity_type=row.opportunity_type,
            item_name=row.item_name,
            supplier_name=row.supplier_name,
            title=row.title,
            summary=row.summary,
            reasoning=row.reasoning,
            recommended_action=row.recommended_action,
            estimated_impact=Decimal(row.estimated_impact),
            risks=row.risks,
            next_steps=row.next_steps or [],
            confidence_score=Decimal(row.confidence_score),
            model_name=row.model_name,
            prompt_version=row.prompt_version,
            created_at=row.created_at,
        )

    @staticmethod
    def _base_query():
        return (
            select(
                AIRecommendation.recommendation_id,
                AIRecommendation.opportunity_id,
                CostOpportunity.opportunity_type,
                Item.item_name,
                Supplier.supplier_name,
                AIRecommendation.title,
                AIRecommendation.summary,
                AIRecommendation.reasoning,
                AIRecommendation.recommended_action,
                AIRecommendation.estimated_impact,
                AIRecommendation.risks,
                AIRecommendation.next_steps,
                CostOpportunity.confidence_score,
                AIRecommendation.model_name,
                AIRecommendation.prompt_version,
                AIRecommendation.created_at,
            )
            .join(
                CostOpportunity,
                AIRecommendation.opportunity_id == CostOpportunity.opportunity_id,
            )
            .join(Item, CostOpportunity.item_id == Item.item_id)
            .outerjoin(Supplier, CostOpportunity.supplier_id == Supplier.supplier_id)
        )

    def recommendations(
        self,
        pagination: PaginationParams,
        *,
        opportunity_type: str | None = None,
    ) -> PaginatedResponse[RecommendationResponse]:
        conditions = []
        if opportunity_type:
            conditions.append(CostOpportunity.opportunity_type == opportunity_type)
        base = self._base_query().where(*conditions)
        total = self.session.scalar(select(func.count()).select_from(base.subquery())) or 0
        rows = self.session.execute(
            base.order_by(AIRecommendation.created_at.desc())
            .offset(pagination.offset)
            .limit(pagination.page_size)
        ).all()
        return PaginatedResponse.create(
            items=[self._response(row) for row in rows],
            total=int(total),
            pagination=pagination,
        )

    def recommendation(self, recommendation_id: int) -> RecommendationResponse | None:
        row = self.session.execute(
            self._base_query().where(AIRecommendation.recommendation_id == recommendation_id)
        ).one_or_none()
        return self._response(row) if row else None
